apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: osm-pota-map-sealed-secrets
  namespace: ea7klk
  labels:
    fleet.spainip.es/workspace: ea7klk
  annotations:
    helm.sh/resource-policy: keep
spec:
  repo: https://github.com/ea7klk/OSM-POTA-Map.git
  branch: main
  paths:
    - fleet/sealed-secrets
  keepResources: true
  correctDrift:
    enabled: true
